[versions]
android-gradle-plugin = "8.7.3"
android-library-plugin = "8.2.2"

kotlin = "2.1.0"
kotlinx-serialization = "1.7.3"

auth0 = "2.9.2"
auth0-jwtdecode = "2.0.1"

android-core = "1.13.1"
app-compat = "1.7.0"
material = "1.12.0"
constraint-layout = "2.2.0"
ktor = "3.0.2"
androidx-activity = "1.9.3"
androidx-lifecycle = "2.8.6"
androidx-browser = "1.8.0"
androidx-test-junit = "1.2.1"
dokka = "1.9.20"

compose = "1.7.6"
compose-activity = "1.9.3"
kotlin-compiler-extension = "1.5.15"

junit = "4.13.2"
androidx-test-espresso = "3.6.1"

nexus-plugin = "2.0.0"
kotlinter = "5.0.1"

jedlix-sdk = "1.8.2"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android-core" }
androidx-app-compat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat" }
androix-constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint-layout" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity"}
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle"}
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser"}

auth0 = { module = "com.auth0.android:auth0", version.ref = "auth0" }
auth0-jwtdecode = { module = "com.auth0.android:jwtdecode", version.ref = "auth0-jwtdecode" }

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }

material = { module = "com.google.android.material:material", version.ref = "material" }


ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }


junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core",  version.ref = "androidx-test-espresso"}

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

jedlix-sdk = { module = "com.jedlix:sdk", version.ref = "jedlix-sdk" }

[plugins]
kotlinter-plugin = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-plugin" }
android-library = { id = "com.android.library", version.ref = "android-library-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }